# Generated by Django 4.1 on 2022-08-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(default=18)),
                ("health", models.CharField(max_length=30)),
                ("employeed", models.BooleanField(default=False)),
                ("businessOwner", models.BooleanField(default=False)),
                ("married", models.BooleanField(default=False)),
                ("homeOwner", models.BooleanField(default=False)),
                ("renting", models.BooleanField(default=False)),
                ("student", models.BooleanField(default=False)),
                ("haveChildren", models.BooleanField(default=False)),
            ],
        ),
    ]
