# Generated by Django 4.1 on 2022-08-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="employeed",
            new_name="employed",
        ),
    ]
